# Generated by Django 5.1.2 on 2024-12-05 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_buy_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dis',
            field=models.TextField(default='dis'),
            preserve_default=False,
        ),
    ]
