# Generated by Django 4.2.16 on 2025-01-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_product_dis_remove_product_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dis',
            field=models.TextField(default='j'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.FileField(default='size', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='offer_price',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default='2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='pro_id',
            field=models.TextField(default='pro_id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(),
        ),
    ]
