# Generated by Django 4.2.16 on 2025-02-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_product_dis_product_img_product_offer_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='email',
            field=models.EmailField(default='a', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='phone_number',
            field=models.CharField(default='a', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_address',
            field=models.TextField(default='f'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
