# Generated by Django 4.2.16 on 2025-02-03 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_booking_date_booking_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='date',
        ),
    ]
