# Generated by Django 5.1.5 on 2025-02-07 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_cart_quantity_alter_product_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='quantity',
            new_name='quantitty',
        ),
    ]
