# Generated by Django 5.1.2 on 2025-02-10 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_buy_quantity_buy_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='quantitty',
            new_name='quantity',
        ),
    ]
