# Generated by Django 5.1.6 on 2025-02-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_rename_quantitty_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50),
        ),
    ]
