# Generated by Django 5.1.6 on 2025-03-01 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_order_payment_id_order_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.order'),
        ),
    ]
